### ISSUE TITLE
A Predicition Problem

### ISSUE THREAD

**Issue by ysy-scu** [binbinbinv/GATSol#1]
Traceback (most recent call last):
  File "/root/autodl-tmp/shiyang/GATSol/Predict/./tools/Predict.py", line 83, in <module>
    with open(file_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './NEED_to_PREPARE/pkl/BSGC10062881.pkl'
Hi , I have this problem in using prediction function, but I don't know why.
Best

**Comment by binbinbinv** [comment]
Hi,
Thank you for trying to use GATSol. The GATSol process requires generating a protein graph for each protein and storing it in a .pkl file. During the execution of iFeatureOmegaCLI, there might be instances where certain proteins fail to generate the corresponding feature files, leading to the inability to create the respective protein graphs. 
We are working on fixing this issue, which might take some time. In the meantime, if you have multiple proteins to predict, you can try removing the proteins that cause similar errors, allowing you to obtain prediction results for the remaining proteins.
Best regards

**Comment by binbinbinv** [comment]
> Traceback (most recent call last): File "/root/autodl-tmp/shiyang/GATSol/Predict/./tools/Predict.py", line 83, in with open(file_path, 'rb') as f: FileNotFoundError: [Errno 2] No such file or directory: './NEED_to_PREPARE/pkl/BSGC10062881.pkl' Hi , I have this problem in using prediction function, but I don't know why. Best

Hi,
Thank you for trying to use GATSol. The GATSol process requires generating a protein graph for each protein and storing it in a .pkl file. During the execution of iFeatureOmegaCLI, there might be instances where certain proteins fail to generate the corresponding feature files, leading to the inability to create the respective protein graphs.
We are working on fixing this issue, which might take some time. In the meantime, if you have multiple proteins to predict, you can try removing the proteins that cause similar errors, allowing you to obtain prediction results for the remaining proteins.
Best regards
